// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/rpc_payment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount           float32 `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	BankCode         string  `protobuf:"bytes,2,opt,name=bankCode,proto3" json:"bankCode,omitempty"`
	OrderDescription string  `protobuf:"bytes,3,opt,name=orderDescription,proto3" json:"orderDescription,omitempty"`
	OrderType        string  `protobuf:"bytes,4,opt,name=orderType,proto3" json:"orderType,omitempty"`
	IpAddr           string  `protobuf:"bytes,5,opt,name=ipAddr,proto3" json:"ipAddr,omitempty"`
	ExpireDate       int64   `protobuf:"varint,6,opt,name=expireDate,proto3" json:"expireDate,omitempty"`
}

func (x *CreateBillReq) Reset() {
	*x = CreateBillReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_payment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillReq) ProtoMessage() {}

func (x *CreateBillReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_payment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillReq.ProtoReflect.Descriptor instead.
func (*CreateBillReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBillReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateBillReq) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *CreateBillReq) GetOrderDescription() string {
	if x != nil {
		return x.OrderDescription
	}
	return ""
}

func (x *CreateBillReq) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *CreateBillReq) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *CreateBillReq) GetExpireDate() int64 {
	if x != nil {
		return x.ExpireDate
	}
	return 0
}

type CreateBillRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UuidBill string `protobuf:"bytes,1,opt,name=uuidBill,proto3" json:"uuidBill,omitempty"`
	HrefVnp  string `protobuf:"bytes,2,opt,name=hrefVnp,proto3" json:"hrefVnp,omitempty"`
}

func (x *CreateBillRes) Reset() {
	*x = CreateBillRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_payment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRes) ProtoMessage() {}

func (x *CreateBillRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_payment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRes.ProtoReflect.Descriptor instead.
func (*CreateBillRes) Descriptor() ([]byte, []int) {
	return file_proto_rpc_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBillRes) GetUuidBill() string {
	if x != nil {
		return x.UuidBill
	}
	return ""
}

func (x *CreateBillRes) GetHrefVnp() string {
	if x != nil {
		return x.HrefVnp
	}
	return ""
}

var File_proto_rpc_payment_proto protoreflect.FileDescriptor

var file_proto_rpc_payment_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc5, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61,
	0x6e, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61,
	0x6e, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x44, 0x61, 0x74, 0x65, 0x22, 0x45, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x75, 0x69,
	0x64, 0x42, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x75, 0x69,
	0x64, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x72, 0x65, 0x66, 0x56, 0x6e, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x72, 0x65, 0x66, 0x56, 0x6e, 0x70, 0x32,
	0x49, 0x0a, 0x0b, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rpc_payment_proto_rawDescOnce sync.Once
	file_proto_rpc_payment_proto_rawDescData = file_proto_rpc_payment_proto_rawDesc
)

func file_proto_rpc_payment_proto_rawDescGZIP() []byte {
	file_proto_rpc_payment_proto_rawDescOnce.Do(func() {
		file_proto_rpc_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rpc_payment_proto_rawDescData)
	})
	return file_proto_rpc_payment_proto_rawDescData
}

var file_proto_rpc_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rpc_payment_proto_goTypes = []interface{}{
	(*CreateBillReq)(nil), // 0: proto.CreateBillReq
	(*CreateBillRes)(nil), // 1: proto.CreateBillRes
}
var file_proto_rpc_payment_proto_depIdxs = []int32{
	0, // 0: proto.BillService.CreateBill:input_type -> proto.CreateBillReq
	1, // 1: proto.BillService.CreateBill:output_type -> proto.CreateBillRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rpc_payment_proto_init() }
func file_proto_rpc_payment_proto_init() {
	if File_proto_rpc_payment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rpc_payment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_payment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rpc_payment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rpc_payment_proto_goTypes,
		DependencyIndexes: file_proto_rpc_payment_proto_depIdxs,
		MessageInfos:      file_proto_rpc_payment_proto_msgTypes,
	}.Build()
	File_proto_rpc_payment_proto = out.File
	file_proto_rpc_payment_proto_rawDesc = nil
	file_proto_rpc_payment_proto_goTypes = nil
	file_proto_rpc_payment_proto_depIdxs = nil
}
